/*
    Client 1 = longtime client, lots of placements
    Client 2 = 2 year client, hasn't placed in 1 year
    Client 3 =
    Client 4 = inactive client
    Client 5 = onboarding client
*/

const clients = [
    {
      id: 'my-1',
      clientId: 'CLT-1001',
      companyName: 'Apex Properties',
      assignedRepId: 'client-rep-002',
      createdDate: '2021-03-15',
      createdClientDate: '2021-03-15',
      activeClientDate: '2021-04-01',
      archiveDate: null,
      dbas: ['Apex Residential'],
      isCorporate: true,
      corporateId: 'CORP-1001',
      firstFilePlacementDate: '2021-06-01',
      mostRecentFilePlacementDate: '2025-11-15',
      clientStatus: 'ACTIVE',
      prospectStatus: null,
      website: 'https://apex.example.com',
      linkedIn: 'https://linkedin.com/company/apex-properties',
      address1: '1500 Blake St',
      address2: 'Suite 400',
      city: 'Denver',
      state: 'CO',
      zipCode: '80202',
      contactIds: ['contact-seed-my-1'],
      unitCount: 3200
    },
    {
      id: 'my-2',
      clientId: 'CLT-1002',
      companyName: 'Bell Management',
      assignedRepId: 'client-rep-002',
      createdDate: '2020-08-20',
      createdClientDate: '2020-08-20',
      activeClientDate: '2020-09-10',
      archiveDate: null,
      dbas: [],
      isCorporate: true,
      corporateId: 'CORP-1002',
      firstFilePlacementDate: '2020-10-15',
      mostRecentFilePlacementDate: '2026-01-20',
      clientStatus: 'ACTIVE',
      prospectStatus: null,
      website: 'https://bell.example.com',
      linkedIn: 'https://linkedin.com/company/bell-management',
      address1: '500 Congress Ave',
      address2: null,
      city: 'Austin',
      state: 'TX',
      zipCode: '78701',
      contactIds: ['contact-seed-my-2'],
      unitCount: 8500
    },
    {
      id: 'my-3',
      clientId: 'CLT-1003',
      companyName: 'Cascade Housing',
      assignedRepId: 'client-rep-002',
      createdDate: '2022-01-10',
      createdClientDate: '2022-01-10',
      activeClientDate: '2022-02-01',
      archiveDate: null,
      dbas: ['Cascade Communities'],
      isCorporate: false,
      corporateId: 'CORP-1003',
      firstFilePlacementDate: '2022-03-05',
      mostRecentFilePlacementDate: '2025-08-12',
      clientStatus: 'ACTIVE',
      prospectStatus: null,
      website: 'https://cascade.example.com',
      linkedIn: 'https://linkedin.com/company/cascade-housing',
      address1: '1700 Lincoln St',
      address2: null,
      city: 'Denver',
      state: 'CO',
      zipCode: '80203',
      contactIds: ['contact-seed-my-3'],
      unitCount: 2150
    },
    {
      id: 'all-4',
      clientId: 'CLT-1004',
      companyName: 'Dreamscape Residential Housing',
      assignedRepId: 'client-rep-005',
      createdDate: '2022-09-12',
      createdClientDate: '2022-09-12',
      activeClientDate: null,
      archiveDate: null,
      dbas: [],
      isCorporate: true,
      corporateId: 'CORP-1014',
      firstFilePlacementDate: null,
      mostRecentFilePlacementDate: '2026-02-25',
      clientStatus: 'PROSPECTING',
      prospectStatus: 'IN_COMMUNICATION',
      website: 'https://dreamscape.example.com',
      linkedIn: 'https://linkedin.com/company/dreamscape-housing',
      address1: '200 W Monroe St',
      address2: 'Floor 12',
      city: 'Chicago',
      state: 'IL',
      zipCode: '60606',
      contactIds: ['contact-seed-all-4'],
      unitCount: 3900
    },
    {
        id: 'all-5',
        clientId: 'CLT-1005',
        companyName: 'Everclear Properties',
        assignedRepId: 'client-rep-005',
        createdDate: '2022-09-12',
        createdClientDate: '2022-09-12',
        activeClientDate: null,
        archiveDate: null,
        dbas: [],
        isCorporate: true,
        corporateId: 'CORP-1014',
        firstFilePlacementDate: null,
        mostRecentFilePlacementDate: '2026-02-25',
        clientStatus: 'PROSPECTING',
        prospectStatus: 'IN_COMMUNICATION',
        website: 'https://everclear.example.com',
        linkedIn: 'https://linkedin.com/company/everclear-housing',
        address1: '200 W Monroe St',
        address2: 'Floor 12',
        city: 'Chicago',
        state: 'IL',
        zipCode: '60606',
        contactIds: ['contact-seed-all-4'],
        unitCount: 3900
      }
  ];

module.exports = {
  clients
};
