// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const USER = 'lmerr72';
const PASSWORD = '';
const HOST = 'localhost';
const PORT = '5432';
const DATABASE = 'ncs180';


const url = `postgresql://${USER}:${PASSWORD}@${HOST}:${PORT}/${DATABASE}`

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: url,
  },
});
